version: "3.7"
services:
  entrepreneur-stack-app:
    build:
      args:
        user: entrepreneur-stack
        uid: 1000
      context: ./
      dockerfile: ./Dockerfile
    image: entrepreneur-stack-backend
    container_name: entrepreneur-stack-backend
    restart: unless-stopped
    env_file: ./.env
    environment:
      APP_ENV: ${APP_ENV}
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - machine-entrepreneur-stack

  nginx:
    image: nginx:1.17-alpine
    container_name: entrepreneur-stack-nginx
    restart: unless-stopped
    ports:
      - 9023:80
    depends_on:
      - entrepreneur-stack-app
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - machine-entrepreneur-stack

  worker-parse:
    image: entrepreneur-stack-backend
    container_name: entrepreneur-stack-worker-parse
    restart: unless-stopped
    entrypoint: "php artisan queue:work --sleep=3 --tries=3"
    volumes:
      - ./:/var/www
    networks:
      - machine-entrepreneur-stack

  schedule-parse:
    image: entrepreneur-stack-backend
    container_name: entrepreneur-stack-schedule-parse
    restart: unless-stopped
    entrypoint: "php artisan schedule:work"
    volumes:
      - ./:/var/www
    networks:
      - machine-entrepreneur-stack

volumes:
  mysql:
    driver: local

networks:
  machine-entrepreneur-stack:
    driver: bridge
